name: Deploy to TrueFoundry

on:
  workflow_dispatch

env:
  TFY_HOST: https://app.devtest.truefoundry.tech
  TFY_API_KEY: ${{ secrets.TFY_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install servicefoundry
        run: pip install servicefoundry
      - name: Fetch manifest
        run: |
          sfy --json get application --application-fqn=tfy-ctl-euwe1-devtest:my-workspace:my-service | jq '.lastDeployment.manifest' > servicefoundry.json
      - name: Conver to yaml
        id: json2yaml
        uses: fabasoad/yaml-json-xml-converter-action@main
        with:
          path: 'servicefoundry.json'
          from: 'json'
          to: 'yaml'
      - name: Generate servicefoundry-patched.yaml
        run: |
          cat servicefoundry.yaml
          echo "${{ steps.json2yaml.outputs.data }}"
          echo "${{ steps.json2yaml.outputs.data }}" > servicefoundry.yaml
          sfy patch --file servicefoundry.yaml --filter='.image.image_uri = "testcontainers/helloworld' --output-file servicefoundry-patched.yaml
      - name: Deploy
        run: sfy deploy --workspace-fqn tfy-ctl-euwe1-devtest:my-workspace --file servicefoundry-patched.yaml