name: Deploy to TrueFoundry

on:
  workflow_dispatch

env:
  TFY_HOST: https://app.devtest.truefoundry.tech
  TFY_API_KEY: ${{ secrets.TFY_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install servicefoundry
        run: pip install servicefoundry
      - name: Create patch file
        run: |
          echo "image: { image_uri: testcontainers/helloworld }" > patch.yaml
      - name: Deploy with patch
        run: sfy deploy-patch --application_fqn=tfy-ctl-euwe1-devtest:my-workspace:my-service --file=patch.yaml