name: Deploy to TrueFoundry

on:
  workflow_dispatch

env:
  TFY_HOST: https://app.devtest.truefoundry.tech
  TFY_API_KEY: ${{ secrets.TFY_API_KEY }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install servicefoundry
        run: pip install servicefoundry
      - name: Fetch manifest
        run: |
          sfy --json get application --application-fqn=tfy-ctl-euwe1-devtest:my-workspace:my-service | jq '.lastDeployment.manifest' > servicefoundry.json
      - name: Conver to yaml
        run: cat "servicefoundry.json" | yq -P > servicefoundry.yaml
      - name: Generate servicefoundry-patched.yaml
        run: sfy patch --file servicefoundry.yaml --filter='.image.image_uri = "testcontainers/helloworld' --output-file servicefoundry-patched.yaml
      - name: Deploy
        run: sfy deploy --workspace-fqn tfy-ctl-euwe1-devtest:my-workspace --file servicefoundry-patched.yaml