name: Deploy on Truefoundry
on:
  push:
    branches:
      - main

env:
  TFY_API_KEY: ${{ secrets.TFY_API_KEY }}
  TFY_HOST: https://app.devtest.truefoundry.tech

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Deploying ${{ github.ref }} to servicefoundry"
      - name: Fetch manifest
        id: curl
        run: |
          curl --location --request GET https://app.devtest.truefoundry.tech/api/svc/v1/app/clk7xf8kc0mf51hjm92sigv2p/manifest --header 'authorization: Bearer ${{ env.TFY_API_KEY }}' > tfy-manifest.json
      - name: editing SHA
        run: cat "tfy-manifest.json" | jq --arg sha "${{ github.sha }}" '.image.build_source.ref |= $sha' > new-tfy-manifest.json
      - name: Generate servicefoundry-patched.yaml
        run: cat "new-tfy-manifest.json" | yq -P > servicefoundry-patched.yaml
      - name: Install servicefoundry
        run: pip install servicefoundry
      - name: Deploy
        run: sfy deploy --workspace-fqn tfy-ctl-euwe1-devtest:srihari-ws --file servicefoundry-patched.yaml